SELECT SALELIST.SALENO, SHOP.SCODE, 
SHOP.SNAME, SALELIST.SALEDATE,
SALELIST.PCODE, PIZZA.PNAME, 
SALELIST.AMOUNT, PIZZA.COST
FROM tbl_salelist_01 SALELIST, 
tbl_pizza_01 PIZZA, tbl_shop_01 SHOP
WHERE PIZZA.PCODE = SALELIST.PCODE 
AND SHOP.SCODE = SALELIST.SCODE
ORDER BY SALELIST.SALENO ASC;



SELECT SHOP.SCODE, SHOP.SNAME, 
SUM(PIZZA.COST * SALELIST.AMOUNT)
FROM tbl_pizza_01 PIZZA, 
tbl_salelist_01 SALELIST, tbl_shop_01 SHOP
WHERE SHOP.SCODE = SALELIST.SCODE 
AND PIZZA.PCODE = SALELIST.PCODE
GROUP BY SHOP.SCODE, SHOP.SNAME
ORDER BY SHOP.SCODE ASC;



SELECT PIZZA.PCODE, PIZZA.PNAME, 
SUM(PIZZA.COST * SALELIST.AMOUNT) TOTALSALE
FROM tbl_pizza_01 PIZZA, tbl_salelist_01 SALELIST
WHERE PIZZA.PCODE = SALELIST.PCODE
GROUP BY PIZZA.PCODE, PIZZA.PNAME
ORDER BY TOTALSALE DESC;



SELECT PIZZA.PCODE, PIZZA.PNAME
FROM tbl_pizza_01 PIZZA
ORDER BY PIZZA.PCODE ASC;



INSERT INTO TBL_SALELIST_01
(SALENO, SCODE, SALEDATE, PCODE, AMOUNT) 
VALUES('%d', '%s', '%s', '%s', '%s');




CREATE TABLE CHAT_USER (
    USER_ID varchar2(10) not null,
    USER_NAME varchar2(10),
    CONSTRAINT PK_CHAR_USER PRIMARY KEY(USER_ID)
);



CREATE TABLE CHAT (
    CID NUMBER(10) NOT NULL,
    user_id VARCHAR2(10) NOT NULL,
    MESSAGE VARCHAR2(10),
    CONSTRAINT PK_CHAR PRIMARY KEY(CID)
);



CREATE SEQUENCE CHATID
INCREMENT BY 1
START WITH 1;

DROP SEQUENCE CHATID;

SELECT USER_ID, USER_NAME FROM CHAT_USER;



SELECT CHAT_USER.USER_NAME, CHAT.MESSAGE
FROM CHAT_USER, CHAT
WHERE CHAT.USER_ID = CHAT_USER.USER_ID
ORDER BY CHAT.CID ASC;



SELECT CHAT_USER.USER_NAME, CHAT_USER.USER_ID
FROM CHAT_USER;



INSERT INTO CHAT(CID, USER_ID, MESSAGE)
VALUES(CHATID.NEXTVAL, '%S', '%S');